#if DEBUG
import SwiftUI

/// Dev-only changelog + open-action list for the posture-visualization tuning
/// rig. **Scaffolding, not product**: the whole file is `#if DEBUG`, so it is
/// stripped from the Release / TestFlight build the nightly auto-build ships —
/// even though that routine commits this repo. Surfaced in-app behind the ⓘ
/// button in `PostureVisualizationView` so the running session always carries
/// its own "what changed / what's left" memo across rebuilds.
///
/// Maintenance contract: whenever you change the tuning rig, add a line to
/// `changes` (and, if it opens or closes a decision, to `toAction`) and bump
/// `lastUpdated`. Keep entries terse — this is a scan target, not a doc.
enum PostureVisualizationDevNotes {

    static let lastUpdated = "2026-06-20"

    /// What this tuning session has already changed.
    static let changes: [String] = [
        "PITCH JITTER — One Euro source denoise on the head angles (2026-06-20): device report 'pitch still fluctuates, like it's not getting a good read' is a SIGNAL-quality problem, NOT the render smoothing (which the 2026-06-20 follower fixed). Root cause: collapsing the VM head EMA to pass-through (the follower change) removed the ONLY stage that attenuated signal-band noise; the critically-damped follower is a TRACKER not a denoiser, so ARKit's ~0.3–0.5° pitch wobble now passes through the ~5.4× pitch gain (1.5 headRotationAmplification × 0.6 shapeHeadTilt × 6 headPitchGain) unfiltered and the follower faithfully renders it. The tier path was exonerated: computeHeadAngles is all-or-nothing and ARFaceTrackingService holds last-good ~0.5 s, so a tracked face does NOT flip-flop to the noisy legacy-2D pitch. Fix: a pure, headlessly-tested OneEuroFilter (PostureLogic) — adaptive low-pass (Casiez 2012): heavy smoothing when still (kills the jitter), cutoff rises with speed so a real nod barely lags (no fixed lag-vs-noise compromise, unlike re-adding an EMA). Applied per-axis on the RAW head yaw/pitch/roll in the VM ingest BEFORE any gain, driven by PoseSample.timestamp. KEY CONTRACT: the filter is the IDENTITY whenever it can't measure a positive dt (first sample seeds; a non-advancing timestamp passes through) — so the camera-free VM tests, which stamp every frame timestamp:0, are unaffected and all prior exact-value assertions hold; only the live app (advancing timestamps) actually filters. Composes with the follower, not a re-cascade: One Euro denoises the source (adaptive, lag only when still), the follower de-staircases the render (a different job, non-overlapping lag). New 'steady'(minCutoff, lower=steadier) + 'catch-up'(beta, higher=snappier) sliders; HeadAngleFilterTuning defaults 1.0 Hz / 0.05. Render-only risk (head angles never feed scoring). swift test +9 (OneEuroFilterTests 8 + a VM advancing-timestamp denoise test). ADVERSARIAL REVIEW (4 lenses → verify, wf_7299c36c): 0 live bugs. The recurring 'reset the filters on a tracking discontinuity' theme is DELIBERATELY not actioned — the dt-aware filter self-heals (brief drop = moderate-dt ease; long gap = large-dt snap to the FRESH value, never the stale one since xHat is overwritten; backward ts = identity), and a hard reset would instead expose one raw unsmoothed frame on every brief drop (strictly worse). Locked by test_headPitch_trackingLossThenResume_tracksFreshValue_noStaleDrag (VM tests 24→25 green on sim). The derivative-estimator onset lag the review flagged is the One Euro paper's intended dCutoff trade-off — dial it out with 'catch-up' (beta) if a real nod feels draggy.",
        "SMOOTHNESS — dt-aware critically-damped head/torso follower (2026-06-20): device report 'tracking better but still isn't smooth' traced to a STRUCTURAL pulse, not a tuning miss. Head angles are sampled at the pipeline's ~10 Hz (the throttle bounds the heavy Vision/depth work) while the renderer ticks at 60–120 Hz, so the render target is a STAIRCASE. The old fixed-weight slerp is a 1st-order EMA: it lunged ~25% of the gap the frame each 10 Hz sample landed, then decayed over ~6 frames = a ~10 Hz THROB; and a 2nd cascaded VM EMA (α=0.2 @10 Hz, ~0.45 s τ) piled lag on top (worst of both). Replaced BOTH with ONE 2nd-order follower: a pure, headlessly-tested CriticallyDampedScalar (PostureLogic) applied per-quaternion-component in apply(), fed a real dt from the TimelineView wall clock. 2nd-order ⇒ velocity is CONTINUOUS across a step (no pulse — proven by a velocity-ramp unit test that fails a 1st-order filter); dt-aware ⇒ feel invariant to ProMotion 120/thermal (the fixed weight was not); component-wise on the COMBINED quaternion with a shortest-path sign flip ⇒ a nod+turn stays on the short arc (round circle preserved). Collapsed the VM head EMA to pass-through (headSmoothingAlpha=1.0; rotation/scale/opacity/lean untouched, so smoothingAlpha=0.2 + its test stand) so the render follower is the SOLE head temporal filter — removes the cascade lag. Bind.orientationSmoothing (per-frame weight, 0.25) → orientationSmoothTime (SECONDS, default 0.09 ≈ one 10 Hz interval); 'smooth' slider now 0–0.30 s (0 = snap). Render-only risk (head angles never feed scoring). CEILING: a render filter cannot add temporal resolution the source lacks — if a residual 10 Hz position STEPPING survives at fast head speed, the documented next step is the deferred 60 Hz head-angle side-channel (publish the already-computed ARFaceAnchor angles past the throttle).",
        "RETIRED Tier-2 monocular face-fit + DEFAULT .frontFace (2026-06-20): removed the Vision rev-3 joint face-fit head-angle path entirely (FaceAngleConversion + FaceAngleTuning.useFaceAngles, PoseObservation.faceYaw/Pitch/Roll, the PoseService VNDetectFaceRectanglesRequest, the 'face' tuning chip, and their tests) — it never had a regime where it was the right answer: worse than ARFaceAnchor where TrueDepth exists, no better than the legacy 2D formula where it doesn't. computeHeadAngles is now TWO tiers: ARFaceAnchor (Tier 1, .frontFace, authoritative) else legacy 2D (Tier 2, fallback floor for non-TrueDepth + ARFace dropout). Also made .frontFace the DEFAULT camera mode on TrueDepth-capable devices (an explicit persisted choice still wins; non-TrueDepth defaults to .rearDepth, and a stale persisted .frontFace on unsupported hw is still coerced to .front2D). Head angles remain VIZ-ONLY (never feed PostureEngine scoring), so both changes are render-only risk. The rad->deg conversion FaceAngleConversion provided was inlined into HeadOrientationDecomposition.",
        "MODE-GATED turn↓tilt fade for .frontFace (2026-06-20): a workflow trace confirmed a head-circle tracks SMOOTHLY in motion (ARKit source + combined-quaternion slerp) but renders as an OVAL, because the cos(yaw)^tiltTurnFadePower fade (=2.0) is STILL ON and flattens a real circle's left/right extents — that fade only ever existed to cancel the OLD coupled 2D phantom nod, which the decoupled ARFaceAnchor source doesn't produce. Fix: PostureVisualizationBinding.faceTrackingActive (set by AppModel per camera mode) now switches apply() to faceTiltTurnFadePower (default 0 = fade OFF = perfectly round) in .frontFace, leaving the legacy 2D tiltTurnFadePower (2.0) + its tuning untouched. The single turn↓tilt slider edits whichever source is live (activeTiltTurnFadePower), range widened to 0…6. Decomposition itself was exonerated (0.0000° round-trip). Remaining .frontFace non-smoothness is LAG not jitter (VM low-pass alpha=0.2 @10Hz, ~0.45s tau) + a tall/narrow stretch from the anisotropic -0.6/-6/-3 gains — both device-dials, not yet changed.",
        "LAYER 1 — TrueDepth ARFaceAnchor head pose (2026-06-20): monocular Vision pitch proved inadequate on device (pitch still swung with yaw — Vision rev-3 often returns nil pitch, so the per-axis ?? fell back to the coupled legacy 2D pitch). Added a NEW camera mode 'Front (Face)' (CameraMode.frontFace, gated on ARFaceTrackingService.isFaceTrackingSupported) that runs ARFaceTrackingConfiguration: ARFaceAnchor gives a true metric 6-DOF head pose (decoupled by construction, no fallback), while frame.capturedImage still feeds Vision body pose so the device-confirmed SIDE-LEAN survives. Head angles travel as InputFrame.externalHeadAngles -> PoseObservation.externalHeadAngles -> computeHeadAngles Tier 1 (authoritative, NOT gated by the Vision useFaceAngles flag; Tier 2 = Vision fit, Tier 3 = legacy). The matrix->yaw/pitch/roll math is a PURE package fn HeadOrientationDecomposition.taitBryanZYXDegrees (gimbal-safe ZYX, camera-relative inverse(camera)*head, +portraitFixUp) — proven headless: pure-yaw rotation -> |pitch|,|roll|<1e-3 (the W is structurally impossible now). Dropout seam handled: the provider HOLDS last-good angles for ~0.5s when the anchor blips, then releases. swift test 498->511 green; Quant app BUILD SUCCEEDED. DEVICE-CONFIRM: portraitFixUp axis remap (turn=yaw/nod=pitch/tilt=roll) + 3 signs (dial via headYaw/Pitch/RollGain, do NOT pre-invert), drop turn↓tilt toward 1 for this mode (decoupled source emits no phantom), and the ~250ms camera-release settle on mode switch.",
        "SOURCE FIX — Vision joint face-fit (2026-06-19): the W / non-round-circle / phantom-tilt were ONE bug at the SOURCE, not the renderer — PoseDepthFusion computed pitch/yaw/roll as three INDEPENDENT 2D formulas off the same 5 body-pose joints, each assuming the other two axes are 0, so a turn foreshortened the ear line + tipped the projected nose into a phantom nod. Fix sources head angles from Vision rev-3's JOINT face-model fit (VNDetectFaceRectanglesRequestRevision3 → VNFaceObservation.yaw/pitch/roll, run on the SAME front RGB buffer) — three axes from one consistent rotation, decoupled by construction. Stored on optional PoseObservation.faceYaw/Pitch/Roll (NOT the Codable PoseSample — recordings untouched); computeHeadAngles prefers them per-axis with a transparent ?? fallback to the legacy formula (so a strong turn that hides the face still tracks via the body-pose one-ear path). Proven headless: a pure-yaw sweep test asserts |pitch|<1° & |roll|<1° at every yaw where the legacy path injects >10° phantom. LIVE TOGGLE: 'face' chip (next to 'mirror'); default OFF. WHEN YOU FLIP IT ON the head signal's sign + magnitude change, so retune — drop 'turn↓tilt' toward 1 (a decoupled source no longer needs the phantom-cancelling fade; left high it SUPPRESSES a real nod-while-turned), then re-dial head turn/nod/tilt gains (the −6/−3 also amplified the tiny legacy proxy + compensated neck-pivot geometry, so expect smaller magnitudes). Then report the values to bake as the face-path defaults + flip default ON.",
        "W FIX, take 2 — FADE not ADD (2026-06-19): the additive turn→nod decouple couldn't flatten the W on device (raising it bulged the mid-turn, both signs worse) — its fixed sin|yaw| shape didn't match the device's phantom, and an additive term overshoots. Switched to a MULTIPLICATIVE knob: tiltTurnFadePower = exponent on the cos(yaw) tilt-fade (yawAtten = cos(yaw)^p), default 2.0. >1 fades the phantom nod/tilt harder as the head turns — monotone, can only drive toward flat, CAN'T bulge. Trade: also fades a real nod when turned, so a circle flattens slightly at its L/R (set 1.0 for fully round + full W, ~4 for flat turn). 'turn↓tilt' slider (1–6). turnTiltDecouple now defaults 0 (off), slider kept for a future shape-matched model. Fades phantom ROLL too (one knob, both axes).",
        "TURN→NOD DECOUPLE (2026-06-19): a pure left↔right sweep traced a 'W' — 2D pose cross-couples a turn into a phantom nod (~−20° pitch), and the cos(yaw) fade only cancels it at the turn extremes, so the residual peaks at mid-turn (dip mid-left + mid-right = W). Fix: Bind.turnTiltDecouple adds a turn-correlated pitch bias (∝ sin|yaw|, even) to the RAW pitch before shapeHeadTilt, riding the same pipeline as the phantom. Additive + yaw-keyed so it does NOT scale down a real nod (unlike strengthening the fade) — kills the W AND keeps the circle round. 'turn→nod' slider, SIGNED (-2.0…2.0 rad @ full turn). Shipped default 0.0 (OFF) — this additive approach was superseded on device by the multiplicative tiltTurnFadePower fade (see W-FIX take 2 above); slider kept for a future shape-matched phantom model. (The 6°→2° deadzone drop earlier let more phantom through, making the W more visible — this is the proper cancel.)",
        "ROUND HEAD-CIRCLE (2026-06-19): removed the two shape-distorting asymmetries so a physical head-circle renders round. (1) headPitchDownBoost default 6.0→1.0 — an axis-asymmetric nod gain can't make a round circle (chin-down half stretched ~6× the chin-up half); the 6× emphasis is still on the 'nod ↓' slider for whoever wants forward-head emphasis over roundness. (2) headTiltDeadzoneRadians 6°→2° — yaw has no deadzone, so the wider pitch/roll deadzone made small circles start flat-horizontal then pop vertical; the new orientationSmoothing slerp absorbs the jitter the wide deadzone masked. Remaining roundness trim (turn-vs-nod SIZE match) is empirical — use the head turn / head nod sliders; the cos(yaw) tilt-fade still flattens large-circle diagonals slightly by design (anti-phantom-tilt on pure turns).",
        "MOTION SMOOTHING: head + torso orientation now temporally smoothed — apply() slerps the previous rendered pose toward the freshly-resolved target each frame (RuntimeCache.smoothedHead/smoothedTorso persist across frames) instead of snapping. Smooths the COMBINED quaternion, so a nod+turn (head 'circle') eases along the shortest arc and traces a curve rather than each axis jerking. Bind.orientationSmoothing = per-frame slerp weight (1.0 = old snap, 0.25 default ≈60 ms follow @60 fps); 'smooth' slider (0.05–1.0). Fixes the abrupt, non-fluid, non-circular feel.",
        "Head YAW is now PROPORTIONAL past ear occlusion: PoseDepthFusion.oneEarYaw scales the turn off the eyes (θ=atan(k·noseOffset/eyeSep)) instead of snapping to ±60°. Tune k live via the slider (bottom-right ▭ button) — HeadYawTuning.oneEarCalibration, device-tuned default 8.0 (anatomical ideal ≈2.7; Vision keypoints push it higher).",
        "Side lean is now DIRECTIONAL: added RawMetrics.lateralLeanSigned (no abs; abs metric kept for scoring) so the figure leans toward the real side. Confirmed good on device at gain 70 (latLean≈0.059 full lean). Twist also signed (twistSigned) BUT shoulderTwist is shoulder TILT not axial rotation, so it can't read a real twist in 2D.",
        "DEPTH-GATED CHANNELS: forward-lean pitch (headForwardOffset, depth-only) and axial twist are now gated on viewModel.depthActive (pose.depthMode==.depthFusion). Off in 2D so the figure doesn't misbehave on signals it can't see; auto-on under LiDAR. Side lean + head + scale are true 2D and stay live. NOTE: posture SCORING is fully 2D and does NOT use headForwardOffset — dropping these from the viz costs monitoring nothing (PostureEngine thresholds: forwardCreep/twist/lateralLean/headDrop/shoulderRounding).",
        "Tuning panel now focuses on the 2D-inferrable posture types: sliders for side lean, head turn (Bind.headYawGain), head nod (headPitchGain), head tilt (headRollGain), zoom (Mapping.forwardCreepScaleFactor) — all signed display gains, write-through to static vars. Depth-only fwd/twist sliders removed (channels remain in code, depth-gated). Each gain LABEL is a tap-to-toggle for its channel (green=on, dim=off) so a misbehaving gain can be isolated in place; plus mirror + all-on/all-off chips.",
        "Per-posture SOLO: each 2D gain row has an 'iso' button (soloChannel) — one tap switches every other tunable channel off and leaves only this one on, to confirm a posture works in isolation. Depth-only channels (torso-turn/forward-lean) are intentionally NOT in the solo set and not shown on the panel (they need LiDAR; 'torso turning does nothing in 2D' is by design, not a bug). A channelTick @State now nudges the panel so label/iso colours refresh immediately when the non-observable static debug flags flip.",
        "2D gains baked from device tuning (2026-06-19): side lean 70→20 (70 over-tilted), head turn -0.6 (kept), head NOD -6.0 base (reversed from +1.0; headGainRange widened to ±6), head TILT +1.0→-3.0 (reversed), zoom 0.5 (kept). All confirmed correct in isolation via the 'iso' solos.",
        "Asymmetric NOD: the forward (chin-DOWN) nod gets a separate headPitchDownBoost multiplier (default 6.0 ⇒ ≈-36 effective down — the 2D pitch signal is small so it needs a big multiplier) so a forward nod travels further than the chin-up/back move (base -6, which read fine). 'nod ↓' slider (1–8×) tunes it; gated by the same head-nod channel flag (no own toggle).",
        "Side lean is now faded by cos(headYaw)^leanTurnAttenPower (default 1.0, slider 'turn↓lean') so a CHAIR SWIVEL — which shifts the shoulder midpoint like a lean but also turns the face — cancels the lean instead of faking one. Facing camera (yaw≈0) keeps full lean; turned away cancels it. Viz-only; the same false-positive still exists in PostureEngine.lateralLean scoring (separate task).",
        "Per-channel isolation switches added (PostureVisualizationBinding.debug / DebugChannels) — freeze any channel, tune one at a time.",
        "Current debug config: shoulder disc hidden, only HEAD YAW live; every other channel frozen at rest.",
        "Tuning HUD: live channel shown green/bold, frozen channels dimmed; rows grouped HEAD / TORSO / ASSEMBLY.",
        "Left<->right MIRROR toggle added (debug.mirrored) — currently ON. Flips only side-lean, head yaw, head roll, disc twist.",
        "hideGhost + hideHeadBand switches added — currently ON: the faint baseline ghost and the z-fighting tone-divide band are removed for a clean yaw read.",
        "All of the above is #if DEBUG-gated in PostureVisualizationView -> cannot ship via TestFlight even though the repo is auto-committed.",
    ]

    /// Decisions still open / cleanup still owed.
    static let toAction: [String] = [
        "QUATERNION HEAD — device-confirm (Front Face): step the `axis map` index until a head TURN drives figure YAW, a NOD drives PITCH, a TILT drives ROLL (all three correct & same direction as you); toggle `mirror` if left/right is reversed; then a LEVEL left↔right turn must NOT dip (the whole point — the One Euro/over-gain dip is structurally gone on this path). Dial `gain` (1.0 faithful, up for exaggeration) and `max°` (rendered clamp). Report the chosen axis-map index + mirror state + gain/max so they can be baked as defaults (R6). If NO index makes all three axes correct, the screen→figure mapping needs a non-axis-aligned basis — escalate.",
        "PITCH JITTER — dial the One Euro on device (2026-06-20): in 'Front (Face)' mode hold the head STILL and watch the nod. (a) 'steady' slider (minCutoff, default 1.0 Hz) — LOWER it (toward ~0.5) until the held pitch stops shimmering; too low adds a soft hold-lag. (b) 'catch-up' slider (beta, default 0.05) — if a real nod now feels draggy, RAISE it (toward ~0.1); if motion looks jittery while moving, lower it. Dial steady first (kills the reported jitter), then catch-up to recover snap. Bake the pair as HeadAngleFilterTuning defaults once it reads steady-when-still AND responsive-when-moving. (c) FLOOR CHECK — if it's steady when still but still 'not a good read' specifically while you MOVE, that's the 10 Hz source rate aliasing the motion, not the filter: the One Euro can't add temporal resolution the throttle removed — escalate to the same deferred 60 Hz head-angle side-channel noted under SMOOTHNESS (run the filter on the full-rate ARFaceAnchor stream before the Pipeline throttle). (d) SANITY — confirm you are actually in 'Front (Face)' (TrueDepth ARFaceAnchor); a non-TrueDepth fallback sources pitch from the legacy 2D estimate, which is inherently noisier and is a different fix.",
        "SMOOTHNESS — confirm on device (2026-06-20): with the dt-aware critically-damped follower live, (a) DIAL orientationSmoothTime via the 'smooth' slider in the 0.06–0.10 s bracket — too small reintroduces 10 Hz stepping, too large adds visible lag; bake the value that reads smooth-without-lag. (b) FRAME RATE — confirm the follow speed does NOT wobble across 60 Hz vs 120 Hz ProMotion and under thermal throttle (the dt-awareness should hold it steady). (c) ROUND CIRCLE — confirm a blended nod+turn head-circle still traces round (combined-quaternion smoothing should preserve it). (d) CEILING CHECK — if a residual 10 Hz position STEPPING is still visible specifically at FAST head speed (not slow), that's the source rate, not the filter: escalate to the deferred 60 Hz head-angle side-channel (PassthroughSubject of the already-computed HeadAngles on ARFaceTrackingService, read by apply when faceTrackingActive, bypassing the Pipeline throttle). Only that raises true temporal resolution. (e) DROPOUT RECOIL — collapsing the VM head EMA means that when the SHOULDERS are lost (fuse returns nil; the face-hold path is separate) the head now eases to neutral in ~one orientationSmoothTime (~0.09 s) instead of the old ~0.45 s VM ease. It still EASES (critically-damped, not a snap) and is consistent with all other head motion, but confirm it reads as smooth-not-abrupt by covering the lens mid-pose; if abrupt, HOLD the last head target on pose==nil in the ViewModel else-branch instead of zeroing it (matches the observation-lost path, which already holds the last sample).",
        "FRONT (FACE) / TrueDepth — confirm on device (2026-06-20): select the new 'Front (Face)' camera mode (Settings; TrueDepth devices only) and verify: (a) AXIS REMAP — does a head turn drive YAW, a nod PITCH, a tilt ROLL? If two are swapped, change portraitFixUp in ARFaceTrackingService (try -90° about Z, or swap axes). (b) SIGNS — flip headYaw/Pitch/RollGain signs if a motion goes the wrong way (do NOT pre-invert in the decomposition helper). (c) THE PITCH FIX — confirm pitch no longer moves when you turn (the whole point). (d) Drop turn↓tilt toward 1.0 for this mode (decoupled source, no phantom to fade). (e) SIDE-LEAN still works (shoulders via Vision on the ARFace image) — check both shoulders stay framed at arm's length. (f) MODE-SWITCH — toggle rear<->Front(Face)<->Front(2D) a few times; if the incoming camera stalls, raise AppModel.cameraReleaseSettleMs (250ms start). (g) THERMAL — sustained TrueDepth runs the IR projector; watch for throttling. Once dialed, bake a per-mode .frontFace gain set.",
        "Head YAW is sourced from PoseSample.shoulderTwist, NOT real head turn. Decide whether to re-source it from a head-derived signal — a mapping change in PostureVisualizationViewModel, not a constant tweak.",
        "Head ROLL & PITCH use absolute geometry, not calibration-relative — the likely cause of the original permanently-tilted/buggy look. Consider zeroing them against the ghost baseline at calibration.",
        "Tune the remaining axes one at a time (sideLean, headForward, pitch, roll, twist); flip each flag back to true once dialled in.",
        "Decide if MIRROR is permanent product behaviour -> if so, drop the debug.mirrored guard in apply() and always call mirror(t).",
        "metersPerPoint (0.001) and the Mapping amplification/cap constants are still design starting values — confirm by eye during demo recording.",
        "When tuning is finished: reset DebugChannels to defaults and delete the #if DEBUG block in PostureVisualizationView.",
    ]
}

/// Scrollable dev-notes panel shown behind the ⓘ button. Mirrors the visual
/// language of `PostureVisualizationValuesOverlay` (monospaced, ultra-thin
/// material) so the two HUDs read as one toolset.
struct PostureVisualizationNotesOverlay: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 8) {
                Text("DEV NOTES · updated \(PostureVisualizationDevNotes.lastUpdated)")
                    .fontWeight(.semibold)

                Text("CHANGED")
                    .font(.caption2).fontWeight(.bold).foregroundStyle(.secondary)
                ForEach(Array(PostureVisualizationDevNotes.changes.enumerated()), id: \.offset) { _, line in
                    bullet("✓", line, tint: .green)
                }

                Text("TO ACTION")
                    .font(.caption2).fontWeight(.bold).foregroundStyle(.secondary)
                    .padding(.top, 4)
                ForEach(Array(PostureVisualizationDevNotes.toAction.enumerated()), id: \.offset) { _, line in
                    bullet("•", line, tint: .orange)
                }
            }
            .padding(10)
        }
        .font(.system(.caption2, design: .monospaced))
        .frame(maxWidth: 340, maxHeight: 420)
        .background(.ultraThinMaterial)
        .cornerRadius(10)
        .accessibilityElement(children: .combine)
        .accessibilityLabel("Visualization dev notes")
    }

    @ViewBuilder
    private func bullet(_ symbol: String, _ text: String, tint: Color) -> some View {
        HStack(alignment: .firstTextBaseline, spacing: 6) {
            Text(symbol).foregroundStyle(tint)
            Text(text)
                .foregroundStyle(.primary)
                .fixedSize(horizontal: false, vertical: true)
        }
    }
}
#endif
