import SwiftUI

enum VariantRegistry {
    static let allVariants: [VariantDescriptor] = [
        // MARK: - Score-Centric (1–6)
        VariantDescriptor(id: 1, name: "Precision Gauge", category: .scoreCentric, technologies: [.canvas],
                          makeView: { AnyView(Variant1View()) }),
        VariantDescriptor(id: 2, name: "Triadic Rings", category: .scoreCentric, technologies: [.canvas],
                          makeView: { AnyView(Variant2View()) }),
        VariantDescriptor(id: 3, name: "Battery Drain", category: .scoreCentric, technologies: [.canvas],
                          makeView: { AnyView(Variant3View()) }),
        VariantDescriptor(id: 4, name: "Arc Meter", category: .scoreCentric, technologies: [.canvas],
                          makeView: { AnyView(Variant4View()) }),
        VariantDescriptor(id: 5, name: "Numeric Countdown", category: .scoreCentric, technologies: [],
                          makeView: { AnyView(Variant5View()) }),
        VariantDescriptor(id: 6, name: "Traffic Light", category: .scoreCentric, technologies: [],
                          makeView: { AnyView(Variant6View()) }),

        // MARK: - Data Visualization (7–12)
        VariantDescriptor(id: 7, name: "Five-Bar Equalizer", category: .dataVisualization, technologies: [.canvas],
                          makeView: { AnyView(Variant7View()) }),
        VariantDescriptor(id: 8, name: "Donut Breakdown", category: .dataVisualization, technologies: [.canvas],
                          makeView: { AnyView(Variant8View()) }),
        VariantDescriptor(id: 9, name: "Horizontal Rails", category: .dataVisualization, technologies: [],
                          makeView: { AnyView(Variant9View()) }),
        VariantDescriptor(id: 10, name: "Radial Dial Array", category: .dataVisualization, technologies: [.canvas],
                          makeView: { AnyView(Variant10View()) }),
        VariantDescriptor(id: 11, name: "Digital Cockpit", category: .dataVisualization, technologies: [.canvas],
                          makeView: { AnyView(Variant11View()) }),
        VariantDescriptor(id: 12, name: "Split Flap Display", category: .dataVisualization, technologies: [],
                          makeView: { AnyView(Variant12View()) }),

        // MARK: - Typographic (13–20)
        VariantDescriptor(id: 13, name: "Single Word", category: .typographic, technologies: [],
                          makeView: { AnyView(Variant13View()) }),
        VariantDescriptor(id: 14, name: "Breathing Dot", category: .typographic, technologies: [],
                          makeView: { AnyView(Variant14View()) }),
        VariantDescriptor(id: 15, name: "Thin Line", category: .typographic, technologies: [.canvas],
                          makeView: { AnyView(Variant15View()) }),
        VariantDescriptor(id: 16, name: "Gradient Wash", category: .typographic, technologies: [.meshGradient],
                          makeView: { AnyView(Variant16View()) }),
        VariantDescriptor(id: 17, name: "Clock Face", category: .typographic, technologies: [.canvas],
                          makeView: { AnyView(Variant17View()) }),
        VariantDescriptor(id: 18, name: "Emoji Mood", category: .typographic, technologies: [],
                          makeView: { AnyView(Variant18View()) }),
        VariantDescriptor(id: 19, name: "Concentric Ripples", category: .typographic, technologies: [.canvas],
                          makeView: { AnyView(Variant19View()) }),
        VariantDescriptor(id: 20, name: "Kanji / Symbol", category: .typographic, technologies: [],
                          makeView: { AnyView(Variant20View()) }),

        // MARK: - Abstract Geometric (21–28)
        VariantDescriptor(id: 21, name: "Stacked Totem", category: .abstract, technologies: [.canvas],
                          makeView: { AnyView(Variant21View()) }),
        VariantDescriptor(id: 22, name: "Radar Glyph", category: .abstract, technologies: [.canvas],
                          makeView: { AnyView(Variant22View()) }),
        VariantDescriptor(id: 23, name: "Concentric Target", category: .abstract, technologies: [.canvas],
                          makeView: { AnyView(Variant23View()) }),
        VariantDescriptor(id: 24, name: "Pendulum Array", category: .abstract, technologies: [.canvas],
                          makeView: { AnyView(Variant24View()) }),
        VariantDescriptor(id: 25, name: "Tensegrity", category: .abstract, technologies: [.canvas],
                          makeView: { AnyView(Variant25View()) }),
        VariantDescriptor(id: 26, name: "Origami Crane", category: .abstract, technologies: [.canvas],
                          makeView: { AnyView(Variant26View()) }),
        VariantDescriptor(id: 27, name: "Bauhaus Figure", category: .abstract, technologies: [.canvas],
                          makeView: { AnyView(Variant27View()) }),
        VariantDescriptor(id: 28, name: "Sacred Geometry", category: .abstract, technologies: [.canvas],
                          makeView: { AnyView(Variant28View()) }),

        // MARK: - Anatomical / 3D (29–34)
        VariantDescriptor(id: 29, name: "SceneKit Mannequin", category: .anatomical, technologies: [.canvas],
                          makeView: { AnyView(Variant29View()) }),
        VariantDescriptor(id: 30, name: "Wire Skeleton", category: .anatomical, technologies: [.canvas],
                          makeView: { AnyView(Variant30View()) }),
        VariantDescriptor(id: 31, name: "Body Silhouette", category: .anatomical, technologies: [.canvas],
                          makeView: { AnyView(Variant31View()) }),
        VariantDescriptor(id: 32, name: "Muscle Heatmap", category: .anatomical, technologies: [.sceneKit],
                          makeView: { AnyView(Variant32View()) }),
        VariantDescriptor(id: 33, name: "Spine Column", category: .anatomical, technologies: [.canvas],
                          makeView: { AnyView(Variant33View()) }),
        VariantDescriptor(id: 34, name: "Mirror Avatar", category: .anatomical, technologies: [.canvas],
                          makeView: { AnyView(Variant34View()) }),

        // MARK: - Instruments (35–40)
        VariantDescriptor(id: 35, name: "Attitude Indicator", category: .experimental, technologies: [.canvas],
                          makeView: { AnyView(Variant35View()) }),
        VariantDescriptor(id: 36, name: "Spirit Level", category: .experimental, technologies: [.canvas],
                          makeView: { AnyView(Variant36View()) }),
        VariantDescriptor(id: 37, name: "Gyroscope Rings", category: .experimental, technologies: [.canvas],
                          makeView: { AnyView(Variant37View()) }),
        VariantDescriptor(id: 38, name: "Compass Rose", category: .experimental, technologies: [.canvas],
                          makeView: { AnyView(Variant38View()) }),
        VariantDescriptor(id: 39, name: "Oscilloscope", category: .experimental, technologies: [.canvas],
                          makeView: { AnyView(Variant39View()) }),
        VariantDescriptor(id: 40, name: "Load Diagram", category: .experimental, technologies: [.canvas],
                          makeView: { AnyView(Variant40View()) }),

        // MARK: - Ambient / Atmospheric — Organic / Nature (41–46)
        VariantDescriptor(id: 41, name: "Wilting Plant", category: .ambient, technologies: [.canvas],
                          makeView: { AnyView(Variant41View()) }),
        VariantDescriptor(id: 42, name: "Tree of Life", category: .ambient, technologies: [.canvas],
                          makeView: { AnyView(Variant42View()) }),
        VariantDescriptor(id: 43, name: "Water Surface", category: .ambient, technologies: [.metal],
                          makeView: { AnyView(Variant43View()) }),
        VariantDescriptor(id: 44, name: "Terrain Map", category: .ambient, technologies: [.canvas],
                          makeView: { AnyView(Variant44View()) }),
        VariantDescriptor(id: 45, name: "Weather System", category: .ambient, technologies: [.canvas],
                          makeView: { AnyView(Variant45View()) }),
        VariantDescriptor(id: 46, name: "Coral Reef", category: .ambient, technologies: [.canvas],
                          makeView: { AnyView(Variant46View()) }),

        // MARK: - Ambient / Atmospheric — Shader-Driven (47–54)
        VariantDescriptor(id: 47, name: "Aurora Borealis", category: .ambient, technologies: [.metal],
                          makeView: { AnyView(Variant47View()) }),
        VariantDescriptor(id: 48, name: "Turbulent Flow", category: .ambient, technologies: [.metal, .canvas],
                          makeView: { AnyView(Variant48View()) }),
        VariantDescriptor(id: 49, name: "Frosted Glass", category: .ambient, technologies: [.canvas],
                          makeView: { AnyView(Variant49View()) }),
        VariantDescriptor(id: 50, name: "Chromatic Split", category: .ambient, technologies: [.metal],
                          makeView: { AnyView(Variant50View()) }),
        VariantDescriptor(id: 51, name: "Glitch Matrix", category: .ambient, technologies: [.metal],
                          makeView: { AnyView(Variant51View()) }),
        VariantDescriptor(id: 52, name: "Lava Lamp", category: .ambient, technologies: [.canvas],
                          makeView: { AnyView(Variant52View()) }),
        VariantDescriptor(id: 53, name: "Heartbeat Pulse", category: .ambient, technologies: [.canvas],
                          makeView: { AnyView(Variant53View()) }),
        VariantDescriptor(id: 54, name: "Starfield", category: .ambient, technologies: [.canvas],
                          makeView: { AnyView(Variant54View()) }),

        // MARK: - Gamified (55–58)
        VariantDescriptor(id: 55, name: "XP Health Bar", category: .gamified, technologies: [.canvas],
                          makeView: { AnyView(Variant55View()) }),
        VariantDescriptor(id: 56, name: "Streak Counter", category: .gamified, technologies: [],
                          makeView: { AnyView(Variant56View()) }),
        VariantDescriptor(id: 57, name: "Achievement Rings", category: .gamified, technologies: [.canvas],
                          makeView: { AnyView(Variant57View()) }),
        VariantDescriptor(id: 58, name: "Boss Battle", category: .gamified, technologies: [.canvas],
                          makeView: { AnyView(Variant58View()) }),

        // MARK: - Experimental — Architectural (59–60)
        VariantDescriptor(id: 59, name: "Torii Gate", category: .experimental, technologies: [.canvas],
                          makeView: { AnyView(Variant59View()) }),
        VariantDescriptor(id: 60, name: "Suspension Bridge", category: .experimental, technologies: [.canvas],
                          makeView: { AnyView(Variant60View()) }),
    ]
}
